name: Deploy Golang server
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t Sabyradinov/go-server -f Dockerfile.dev .
      - run: docker run -e CI=true Sabyradinov/go-server go test -cover ./...